stages:
  - backendDocker

backend-docker:
  stage: backendDocker
  tags:
    - backend
  script:
    - cd Backend
    - sudo docker compose down
    - sudo docker compose build
    - sudo docker compose up -d