stages:
  - mavenbuild
  - maventest
  
maven-build:            
  stage: mavenbuild
  tags:
    - phun_tag      # <-- change to your runner's tag
  script:
    - cd Backend/api        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package
  only:
    refs:
      - PHUN_CICD
    changes:
      - Backend/**/*

maven-test:             
  stage: maventest
  tags:
    - phun_tag     # <-- change to your runner's tag
  script:
    - cd Backend/api       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test
  only:
    refs:
      - PHUN_CICD
    changes:
      - Backend/**/*
