stages:
  - baackendDebug
  - backendDockerDeploy

backend-debug:
  stage: baackendDebug
  tags:
    - backend
  script:
    - echo "CI_PIPELINE_SOURCE $CI_PIPELINE_SOURCE"
    - echo "CI_COMMIT_REF_NAME $CI_COMMIT_REF_NAME"

backend-docker:
  stage: backendDockerDeploy
  tags:
    - backend
  script:
    - cd Backend
    - sudo docker compose down
    - sudo docker compose build
    - sudo docker compose up -d
  only:
    variables:
    - $CI_PIPELINE_SOURCE == "web"
    - $CI_COMMIT_REF_NAME == "main"
  