name: ${TEST_ID}-backend-test

services:
  harmonize-db:
    build: ./db
    networks:
      - ${TEST_ID}-harmonize-net-test
    environment:
      MYSQL_ROOT_PASSWORD: adminpw
      MYSQL_DATABASE: harmonize-db
      MYSQL_USER: harmonize
      MYSQL_PASSWORD: harmonizepw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  harmonize-api:
    build: ./api
    entrypoint: mvn clean test
    depends_on:
      harmonize-db:
        condition: service_healthy
    networks:
      - ${TEST_ID}-harmonize-net-test

networks:
  ${TEST_ID}-harmonize-net-test:
    driver: bridge
